@startuml
!define ENTITY class
!define PRIMARY_KEY "+"
!define FOREIGN_KEY "()"
!define END_ENTITY

ENTITY ContactManagement {
  - id: long
  - firstName: String
  - surname: String
  - phoneNumber: String
  - email: String
  - address: String
  - password: String
  - isLocked: boolean
  - PRIMARY_KEY id
}

ENTITY Contact {
  - id: long
  - contactManagementId: long
  - firstName: String
  - surname: String
  - phoneNumber: String
  - email: String
  - address: String
  - password: String
  - isBlocked: boolean
  - userEmail: String
  - PRIMARY_KEY id


}

ContactManagement --o{ Contact

@enduml